# Branch based labels
feat:
  - head-branch:
    - "^feat/"

feature:
  - head-branch:
    - "^feature/"

hotfix:
  - head-branch:
    - "^hotfix/"

fix:
  - head-branch:
    - "^fix/"

docs:
  - head-branch:
    - "^docs/"

refactor:
  - head-branch:
    - "^refactor/"

chore:
  - head-branch:
    - "^chore/"

security:
  - head-branch:
    - "^security/"

# Folder based labels

ci:
  - changed-files:
    - any-glob-to-any-file: ".github/workflows/**"
  - head-branch:
    - "^ci/"

monaco-editor:
  - changed-files:
    - any-glob-to-any-file: "packages/monaco-editor/**"

monaco-editor/readme:
  - changed-files:
    - any-glob-to-any-file: "packages/monaco-editor/README.md"

monaco-editor/tests:
  - changed-files:
    - any-glob-to-any-file: "packages/monaco-editor/**/*.spec.ts"

changelog:
  - changed-files:
    - any-glob-to-any-file: "CHANGELOG.md"

dependency:
  - changed-files:
    - any-glob-to-any-file: "package.json"
    - any-glob-to-any-file: "package-lock.json"

scripts:
  - changed-files:
    - any-glob-to-any-file: "scripts/**"
