# Branch based labels
feat:
  - head-branch:
    - "^feat/"

feature:
  - head-branch:
    - "^feature/"

hotfix:
  - head-branch:
    - "^hotfix/"

fix:
  - head-branch:
    - "^fix/"

docs:
  - head-branch:
    - "^docs/"

refactor:
  - head-branch:
    - "^refactor/"

chore:
  - head-branch:
    - "^chore/"

security:
  - head-branch:
    - "^security/"

# Folder based labels
ci:
  - changed-files:
    - any-glob-to-any-file: ".github/workflows/**"
  - head-branch:
    - "^ci/"

monaco-editor:
  - changed-files:
    - any-glob-to-any-file: "packages/monaco-editor/**"

monaco-editor/readme:
  - changed-files:
    - any-glob-to-any-file: "packages/monaco-editor/README.md"

monaco-editor/tests:
  - changed-files:
    - any-glob-to-any-file: "packages/monaco-editor/**/*.spec.ts"

utils:
  - changed-files:
    - any-glob-to-any-file: "packages/utils/**"

utils/readme:
  - changed-files:
    - any-glob-to-any-file: "packages/utils/README.md"

utils/components:
  - changed-files:
    - any-glob-to-any-file: "packages/utils/src/components/**"
    - any-glob-to-any-file: "packages/utils/**/*.component.ts"

utils/directives:
  - changed-files:
    - any-glob-to-any-file: "packages/utils/src/directives/**"
    - any-glob-to-any-file: "packages/utils/**/*.directive.ts"

utils/guards:
  - changed-files:
    - any-glob-to-any-file: "packages/utils/src/guards/**"
    - any-glob-to-any-file: "packages/utils/**/*.guard.ts"

utils/interceptors:
  - changed-files:
    - any-glob-to-any-file: "packages/utils/src/interceptors/**"
    - any-glob-to-any-file: "packages/utils/**/*.interceptor.ts"

utils/pipes:
  - changed-files:
    - any-glob-to-any-file: "packages/utils/src/pipes/**"
    - any-glob-to-any-file: "packages/utils/**/*.pipe.ts"

utils/services:
  - changed-files:
    - any-glob-to-any-file: "packages/utils/src/services/**"
    - any-glob-to-any-file: "packages/utils/**/*.service.ts"

utils/utils:
  - changed-files:
    - any-glob-to-any-file: "packages/utils/src/utils/**"
    - any-glob-to-any-file: "packages/utils/**/*.utils.ts"

utils/modules:
  - changed-files:
    - any-glob-to-any-file: "packages/utils/src/modules/**"
    - any-glob-to-any-file: "packages/utils/**/*.module.ts"

utils/tests:
  - changed-files:
    - any-glob-to-any-file: "packages/utils/**/*.spec.ts"

changelog:
  - changed-files:
    - any-glob-to-any-file: "CHANGELOG.md"

dependency:
  - changed-files:
    - any-glob-to-any-file: "package.json"
    - any-glob-to-any-file: "package-lock.json"

scripts:
  - changed-files:
    - any-glob-to-any-file: "scripts/**"
