ci:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/**'

monaco-editor:
  - changed-files:
      - any-glob-to-any-file: 'packages/monaco-editor/**'

monaco-editor-readme:
  - changed-files:
      - any-glob-to-any-file: 'packages/monaco-editor/README.md'

test:
  - changed-files:
      - any-glob-to-any-file: '**.spec.ts'

readme:
  - changed-files:
      - any-glob-to-any-file: 'README.md'

changelog:
  - changed-files:
      - any-glob-to-any-file: 'CHANGELOG.md'

dependency:
  - changed-files:
      - any-glob-to-any-file: 'package.json'
      - any-glob-to-any-file: 'package-lock.json'

scripts:
  - changed-files:
      - any-glob-to-any-file: 'scripts/**'

feature:
  - head-branch: ['^feature-']

hotfix:
  - head-branch: ['^hotfix-']

refactor:
  - head-branch: ['^refactor-']
