coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 5%
    patch:
      default:
        target: 75%
        threshold: 5%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

flags:
  unit:
    paths:
      - "src/"
    carryforward: true

github_checks:
  annotations: true

